# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:

  name: Azure Pipelines

  demands: maven

  vmImage:  'ubuntu-16.04'



steps:

- task: Maven@3

  displayName: 'Maven pom.xml'



- task: CopyFiles@2

  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'

  inputs:

    SourceFolder: '$(system.defaultworkingdirectory)'

    Contents: 'target/*.jar'

    TargetFolder: '$(build.artifactstagingdirectory)'



- task: PublishBuildArtifacts@1

  displayName: 'Publish Artifact: drop'

  inputs:

    PathtoPublish: '$(build.artifactstagingdirectory)'
